"""A list of all the columns in the fully analysed CSV, mainly cause I hate making typos in column names"""

TOTAL = "Total"
CLEANED_TEXT = "Cleaned Text"
DAY = "Day"
ENTITIES = "Entities"
EMOTION_LABEL = "Emotion Label"
HOUR = "Hour"
PROFANITY_SCORE = "Profanity Score"
PROFANITY_LABEL = "Profanity Label"
RAW_TEXT = "Raw Text"
SENDER = "Sender"
SENTIMENT_LABEL = "Sentiment Label"
SENTIMENT_SCORE = "Sentiment Score"
TIMESTAMP = "Timestamp"
WORD_COUNT = "Word Count"
