"""Commonly used Div IDs and properties to avoid typos"""

ALIASES = "aliases"
ALIASES_COLORS = "aliases-colors"
CHAT_COUNT = "chat-count"
CHAT_COUNT_MEMORY = "chat-count-memory"
CHILDREN = "children"
CIRCLE = "circle"
COLOR = "color"
CUSTOMIZATION_STORE = "customization-store"
FOR_RESEARCH = "for-research"
PARTICIPANT_COLORS = "participant-colors"
DAQ_THEME = "daq-light-dark-theme"
DATA = "data"
N_CLICKS = "n_clicks"
MESSAGE_COUNT = "message-count"
MESSAGE_COUNT_MEMORY = "message-count-memory"
PARTICIPANTS = "participants"
PARTICIPANTS_ALIASES = "participants-aliases"
PRIVACY = "privacy"
STYLE = "style"
URL = "url"
VALUE = "value"
